using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// The campaign: which zones are played in which order, who holds each one, and what
/// falling to the player unlocks.
///
/// This is the spine the story hangs on, and it is an asset for exactly the reason the
/// level clocks live on a <see cref="LevelSet"/> and the prices on a
/// <see cref="StoreCatalog"/>: <b>a number that decides pacing is content, not code.</b>
/// <see cref="Campaign"/> used to carry its one gate as a const, with a comment saying
/// this asset was where it belonged as soon as there was a ladder to put on it. This is
/// that asset.
///
/// Reordering the campaign is dragging an entry in this list. Moving which zone hands
/// over the bomb is retyping one string. Neither is a code change, and neither needs a
/// scene rebuilt -- the dashboard reads this at runtime and orders its cards by it.
///
/// Generated by FPSKit &gt; Create Campaign and re-stamped by FPSKit &gt; Reset Campaign
/// to Defaults, which follows the same rule as every other generator here: <b>editing
/// the generator does not reach the asset until the reset is run.</b>
/// </summary>
[CreateAssetMenu(menuName = "FPSKit/Campaign", fileName = "Campaign")]
public class CampaignData : ScriptableObject
{
    /// <summary>
    /// One of the villain's children. They are listed separately from the zones because
    /// not every one of them holds a site -- the eldest holds the company, and the last
    /// name on the list is the player -- and because a sibling outlives their zone in
    /// the telling.
    /// </summary>
    [Serializable]
    public class Sibling
    {
        [Tooltip("What the game calls them. Shown on the zone's card and in its beats.")]
        public string displayName = "Auger";

        [Tooltip("What they ran, in a few words: \"the plant\", \"the convoy road\".")]
        public string holding;

        [TextArea(2, 4)]
        [Tooltip("What is said when they go down. Shown once, on the return to the " +
                 "dashboard, and then never again.")]
        public string beat;

        [Tooltip("The boss this sibling is fought as. Empty until the roster has a " +
                 "chassis of their own -- the level set's own boss is used meanwhile, " +
                 "so a sibling with nothing here is still a fight rather than nothing.")]
        public EnemyArchetype archetype;

        [Tooltip("The face on their card. Rendered by FPSKit > Generate Portraits as a " +
                 "still off a company camera, which is what the story says these are.\n\n" +
                 "A beat with no face is a paragraph on a dark screen, and six of those " +
                 "in a row are six paragraphs nobody tells apart.")]
        public Texture2D portrait;
    }

    /// <summary>
    /// One stop on the campaign: an arena, its ladder, and whichever child holds it.
    ///
    /// The zone names its <see cref="LevelSet"/> rather than a scene, because the set is
    /// what stored progress is keyed by -- see
    /// <see cref="ArenaCatalog.Entry.ProgressKey"/> for why a scene name is not stable
    /// enough to key anything on. Pointing at the same asset the catalog does is what
    /// lets the two agree without either one knowing about the other.
    /// </summary>
    [Serializable]
    public class Zone
    {
        [Tooltip("For the inspector and for logs. The card's name comes from the arena " +
                 "catalog, so this never has to match it.")]
        public string displayName;

        [Tooltip("The ladder played here. This is also what the zone is identified by: " +
                 "its arenaScene is the key the player's stars are filed under.")]
        public LevelSet levels;

        [Tooltip("Which sibling holds this zone, as an index into the list above. -1 " +
                 "for a zone nobody holds, which is then never a gate for the next one.")]
        public int siblingIndex = -1;

        [TextArea(2, 5)]
        [Tooltip("The story beat shown on the way in, the first time the player opens " +
                 "this zone.")]
        public string opening;

        [Tooltip("A second name whose beat also plays when this zone falls, or -1.\n\n" +
                 "It exists for one card in the whole campaign: the last zone closes on " +
                 "the person the player just beat and then on the name they have not " +
                 "worked out yet, and those are two different people. Folding both into " +
                 "one paragraph would bury the second under the first.")]
        public int extraBeatSibling = -1;

        [Tooltip("The id of the power handed over when this zone falls, or empty. Same " +
                 "kind of permanent key as a store item's id: renaming one forgets that " +
                 "the player ever earned it.")]
        public string grantsPower;

        /// <summary>
        /// What this zone's progress is filed under -- the level set's own name for the
        /// arena, matching <see cref="ArenaCatalog.Entry.ProgressKey"/>.
        /// </summary>
        public string ProgressKey
            => levels != null && !string.IsNullOrWhiteSpace(levels.arenaScene)
                ? levels.arenaScene
                : "";

        public int LevelCount => levels != null ? levels.Count : 0;

        /// <summary>
        /// The index of the level that has to be beaten for the zone to be finished --
        /// the last one, which is the child themself. -1 on a zone with no ladder.
        /// </summary>
        public int FinalLevelIndex => LevelCount - 1;
    }

    [Header("The opening")]
    [TextArea(4, 10)]
    [Tooltip("What the game says before it says anything else, on a genuinely fresh " +
             "profile. It ends on the one question the game ever asks the player about " +
             "themselves.")]
    public string prologue;

    [Tooltip("The question under it. Kept separate from the prologue so the buttons can " +
             "sit against a line of their own rather than at the end of a paragraph.")]
    public string identityQuestion = "Before we start -- were you a boy, or a girl?";

    [Header("The eight")]
    [Tooltip("The eight, in the order the story names them. A sibling is referred to by " +
             "index, so reordering this list renames who is where -- add to the end.")]
    public List<Sibling> siblings = new List<Sibling>();

    [Header("The ladder")]
    [Tooltip("The zones in the order they are played. The first is always open; every " +
             "one after it needs the child of the zone before to be down.")]
    public List<Zone> zones = new List<Zone>();

    public int ZoneCount => zones != null ? zones.Count : 0;

    public Zone ZoneAt(int index)
        => zones != null && index >= 0 && index < zones.Count ? zones[index] : null;

    public Sibling SiblingAt(int index)
        => siblings != null && index >= 0 && index < siblings.Count ? siblings[index] : null;

    /// <summary>The sibling holding a zone, or null.</summary>
    public Sibling HolderOf(Zone zone)
        => zone != null ? SiblingAt(zone.siblingIndex) : null;

    /// <summary>
    /// Where an arena sits in the campaign, by the key its progress is filed under, or
    /// -1 for an arena the campaign says nothing about.
    ///
    /// <b>-1 is not an error.</b> An arena outside the campaign is ungated rather than
    /// locked forever: the kit is meant to run in levels it did not build, and a new
    /// arena dropped into the catalog must be playable before anybody writes it into
    /// the story.
    /// </summary>
    public int IndexOfArena(string progressKey)
    {
        if (string.IsNullOrEmpty(progressKey) || zones == null) return -1;

        for (int i = 0; i < zones.Count; i++)
            if (zones[i] != null && zones[i].ProgressKey == progressKey) return i;

        return -1;
    }

    public Zone ZoneForArena(string progressKey) => ZoneAt(IndexOfArena(progressKey));
}
