using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// A render of every store item's model, keyed by the item's permanent id. Written by
/// FPSKit > Render Store Items (FPSKitItemRenders), read by <see cref="StorePanel"/> for the
/// picture on each card. An asset rather than fields on the catalog, because the catalog is
/// regenerated by Reset Store and the renders need a graphics device to remake.
/// </summary>
[CreateAssetMenu(menuName = "FPSKit/Item Renders")]
public class ItemRenders : ScriptableObject
{
    [Serializable]
    public class Entry
    {
        public string id;
        public Texture2D texture;
    }

    public List<Entry> entries = new List<Entry>();

    public Texture2D For(string id)
    {
        if (string.IsNullOrEmpty(id)) return null;
        foreach (var e in entries) if (e != null && e.id == id) return e.texture;
        return null;
    }
}
